### ISSUE TITLE
Правки до ДЗ

### ISSUE THREAD

**Issue by Dexter19** [nikolyaelen/nikolaionok.olena#1]
В 1-й ДЗ заповніть файл index.html стандатрною розміткою і запушту в репозиторій(зараз файл пустий).
В лекції 2 заповніть файл README.md.
В 3 лекції де у вас class="exciting" має бути 2-a  id p різними іменами.

**Comment by nikolyaelen** [comment]
Добрий день. Не знаю чи треба сюди відписувати?! Виправила
