### ISSUE TITLE
Правки/уточнення до ДЗ 22

### ISSUE THREAD

**Issue by Dexter19** [nikolyaelen/nikolaionok.olena#7]
6.Знайти всі елементи з класом container. Використовуючи цикл for, вивести на консоль перший елемент для кожного зі знайдених елементів.
Ви можете скористатися властивістю firstElementChild.
Ось код:
const containers = document.getElementsByClassName('container');

for (let i = 0; i < containers.length; i++) {
    console.log(containers[i].firstElementChild); 
}
-----------------------------------------------

**Comment by nikolyaelen** [comment]
добре, дякую за пораду
виправила
