### ISSUE TITLE
Правки/уточнення ДЗ 24

### ISSUE THREAD

**Issue by Dexter19** [nikolyaelen/nikolaionok.olena#9]
Перепишіть функцію iterate, використовуючи масив colors, таким чином, щоб на консоль видавалось повідомлення 'The last iteration!' коли функція виконує останню ітерацію для елементів colors.
Можна зробити компактніше таким чином:
function iterate(item, index, array) {
    console.log(item);
      if (index === array.length - 1) {
        console.log('The last iteration!');
      }
}
   
colors.forEach(iterate);
------------------------------

**Comment by nikolyaelen** [comment]
виправила, дякую
